config_version = 14

[accessibility]
ui_scale = 0.90000000596046448

[bar.default]
center = [ "weather", "spacer_1", "clock", "spacer_2", "active_window" ]
scale = 1.0000000074505806
start = [ "launcher", "workspaces", "spacer_1", "group:g1" ]

[dock]
concave_edge_corners = false
enabled = true
icon_size = 30
item_spacing = 0
launcher_position = "end"
main_axis_padding = 10
margin_edge = 10
pinned = [ "firefox", "kitty", "org.gnome.Nautilus" ]
radius_bottom_left = 20
radius_bottom_right = 20
radius_top_left = 20
radius_top_right = 20
reserve_space = false
show_dots = true
smart_auto_hide = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
font_family = "NotoSans NF"

[theme]
wallpaper_scheme = "m3-monochrome"

[wallpaper]
directory_dark = "/home/hikari/Imagens/Wallpapers"
directory_light = "/home/hikari/Imagens/Wallpapers"
fill_mode = "span"

    [wallpaper.default]
    path = "/home/hikari/Imagens/Wallpapers/gdm.jpeg"

    [wallpaper.last]
    path = "/home/hikari/Imagens/Wallpapers/gdm.jpeg"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/hikari/Imagens/Wallpapers/gdm.jpeg"

[widget.clock]
anchor = true

[widget.network]
show_label = false

[widget.spacer_2]
type = "spacer"

[widget.temp]
show_value = true

[widget.volume]
show_label = false
